# =============================================================================
# Bioinformatiker Salary in Germany — Multi-variant figures
# Auto-generated by scrape_bioinformatiker_salary.py — do not edit by hand.
# Source: data/gehaltsvergleich_all.csv
# =============================================================================

library(ggplot2)
library(dplyr)
library(tidyr)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(patchwork)
library(scales)
library(ggtext)
library(glue)
library(ggrepel)
library(readr)

options(rnaturalearth.use_cache = FALSE)

OUT_DPI  <- 300
DATA_FILE <- "data/gehaltsvergleich_all.csv"

# ── 1. Load & clean ──────────────────────────────────────────────────────────

raw <- read_csv(DATA_FILE, show_col_types = FALSE)

east_states <- c(
  "Brandenburg", "Mecklenburg-Vorpommern", "Sachsen",
  "Sachsen-Anhalt", "Thüringen", "Berlin"
)

salary <- raw |>
  mutate(year = as.integer(year)) |>
  group_by(region, year) |>
  slice_max(scrape_date, n = 1, with_ties = FALSE) |>
  ungroup() |>
  mutate(group = ifelse(region %in% east_states, "East", "West"))

salary_states <- salary |> filter(region != "Deutschland")
salary_de     <- salary |> filter(region == "Deutschland")
snap_2026     <- salary_states |> filter(year == 2026)

west_order <- snap_2026 |> filter(group == "West") |>
  arrange(desc(avg)) |> pull(region)
east_order <- snap_2026 |> filter(group == "East") |>
  arrange(desc(avg)) |> pull(region)
state_order <- c(west_order, east_order)

snap_2026     <- snap_2026     |> mutate(region_f = factor(region, levels = rev(state_order)))
salary_states <- salary_states |> mutate(region_f = factor(region, levels = rev(state_order)))

# ── 2. Shapefile ─────────────────────────────────────────────────────────────

de_sf_base <- ne_states(country = "Germany", returnclass = "sf") |>
  select(name, geometry) |>
  mutate(name = recode(name,
    "North Rhine-Westphalia" = "Nordrhein-Westfalen",
    "Bavaria"                = "Bayern",
    "Hesse"                  = "Hessen",
    "Lower Saxony"           = "Niedersachsen",
    "Rhineland-Palatinate"   = "Rheinland-Pfalz",
    "Saxony"                 = "Sachsen",
    "Saxony-Anhalt"          = "Sachsen-Anhalt",
    "Thuringia"              = "Thüringen"
  ))

make_map_sf <- function(yr_data) {
  de_sf_base |> left_join(yr_data, by = c("name" = "region"))
}

unmatched <- make_map_sf(snap_2026) |> filter(is.na(avg)) |> pull(name)
if (length(unmatched) > 0)
  warning("Unmatched states (grey on map): ", paste(unmatched, collapse = ", "))

# ── 3. Palette & theme ────────────────────────────────────────────────────────

CLR_WEST <- "#2166AC"
CLR_EAST <- "#D6604D"
CLR_DE   <- "#1B7837"
CLR_BG   <- "#F7F7F7"

y_colours <- ifelse(
  levels(snap_2026$region_f) %in% east_states, CLR_EAST, CLR_WEST
)

euro_labels <- label_comma(big.mark = ".", decimal.mark = ",", prefix = "\u20ac")

base_theme <- theme_minimal(base_size = 9) +
  theme(
    plot.background   = element_rect(fill = CLR_BG, colour = NA),
    panel.background  = element_rect(fill = CLR_BG, colour = NA),
    plot.title        = element_markdown(size = 10, face = "bold", margin = margin(b = 2)),
    plot.subtitle     = element_markdown(size = 7.5, colour = "grey45", margin = margin(b = 4)),
    axis.title        = element_text(size = 7.5, colour = "grey35"),
    axis.text         = element_text(size = 7),
    panel.grid.minor  = element_blank(),
    panel.grid.major  = element_line(colour = "grey90", linewidth = 0.3),
    legend.position   = "bottom",
    legend.key.width  = unit(1.4, "cm"),
    legend.key.height = unit(0.28, "cm"),
    legend.text       = element_text(size = 7),
    legend.title      = element_text(size = 7.5)
  )

# ── 4. Panel builders ─────────────────────────────────────────────────────────

build_map_single <- function(yr = 2026) {
  yr_data <- salary_states |> filter(year == yr)
  sf_data <- make_map_sf(yr_data)
  de_avg  <- salary_de |> filter(year == yr) |> pull(avg)
  ggplot(sf_data) +
    geom_sf(aes(fill = avg), colour = "white", linewidth = 0.55) +
    scale_fill_distiller(
      palette = "Blues", direction = 1,
      name    = "\u00d8 Bruttogehalt (\u20ac/Mo.) | Avg. gross salary",
      labels  = euro_labels,
      breaks  = c(3800, 4100, 4400, 4700),
      na.value = "grey80"
    ) +
    labs(
      title    = glue("**A** Average gross salary — Bioinformatiker/in, {yr}"),
      subtitle = glue(
        "National avg. (**DE**): **\u20ac{comma(de_avg, big.mark='.', decimal.mark=',')}**/mo. \u00b7 ",
        "Source: gehaltsvergleich.com"
      )
    ) +
    coord_sf(expand = FALSE) +
    base_theme +
    theme(
      axis.text = element_blank(), axis.ticks = element_blank(),
      panel.grid.major = element_blank(), legend.position = "bottom"
    )
}

build_map_facet <- function() {
  years_to_show <- sort(unique(salary_states$year))
  sf_all <- lapply(years_to_show, function(yr) {
    make_map_sf(salary_states |> filter(year == yr)) |>
      mutate(year_label = as.character(yr))
  }) |> bind_rows()
  ggplot(sf_all) +
    geom_sf(aes(fill = avg), colour = "white", linewidth = 0.3) +
    scale_fill_distiller(
      palette = "Blues", direction = 1,
      name    = "\u00d8 Bruttogehalt (\u20ac/Mo.)",
      labels  = euro_labels,
      breaks  = c(3500, 4000, 4500, 5000),
      na.value = "grey80"
    ) +
    facet_wrap(~year_label, nrow = 2) +
    labs(
      title    = "**A** Avg. gross salary by year — Bioinformatiker/in",
      subtitle = "Source: gehaltsvergleich.com + Wayback Machine"
    ) +
    coord_sf(expand = FALSE) +
    base_theme +
    theme(
      axis.text = element_blank(), axis.ticks = element_blank(),
      panel.grid.major = element_blank(),
      strip.text = element_text(size = 7, face = "bold"),
      legend.position = "bottom"
    )
}

build_dumbbell <- function() {
  de_avg_2026 <- salary_de |> filter(year == 2026) |> pull(avg)
  ggplot(snap_2026) +
    geom_segment(
      aes(x = q1, xend = q3, y = region_f, yend = region_f, colour = group),
      linewidth = 1.1, alpha = 0.5
    ) +
    geom_point(aes(x = q1,  y = region_f, colour = group),
               shape = 21, fill = "white", size = 2.2, stroke = 1.0) +
    geom_point(aes(x = q3,  y = region_f, colour = group),
               shape = 21, fill = "white", size = 2.2, stroke = 1.0) +
    geom_point(aes(x = avg, y = region_f, colour = group),
               shape = 18, size = 3.0) +
    geom_vline(xintercept = de_avg_2026,
               linetype = "dashed", colour = CLR_DE, linewidth = 0.5) +
    annotate("text", x = de_avg_2026 + 60, y = 0.6,
             label = "DE avg.", colour = CLR_DE, size = 2.3, hjust = 0) +
    scale_colour_manual(values = c("West" = CLR_WEST, "East" = CLR_EAST), name = NULL) +
    scale_x_continuous(labels = euro_labels,
                       breaks = c(3500, 4000, 4500, 5000, 5500, 6000, 9000)) +
    labs(
      title    = "**B** Salary distribution by state, 2026",
      subtitle = "\u25cb Q1 &nbsp;\u25c6 Mean &nbsp;\u25cb Q3 \u00b7 West = blue, East = red",
      x = "Gross monthly salary (\u20ac)", y = NULL
    ) +
    base_theme +
    theme(
      panel.grid.major.y = element_blank(),
      legend.position    = "none",
      axis.text.y        = element_text(size = 7, colour = y_colours)
    )
}

build_spaghetti <- function() {
  de_line <- salary_de |> filter(!is.na(avg))
  ggplot(salary_states |> filter(!is.na(avg)),
         aes(x = year, y = avg, group = region, colour = group)) +
    geom_line(linewidth = 0.55, alpha = 0.7) +
    geom_point(size = 1.4, alpha = 0.85) +
    geom_line(data = de_line, aes(x = year, y = avg, group = 1),
              colour = CLR_DE, linewidth = 0.9, linetype = "dashed",
              inherit.aes = FALSE) +
    geom_label_repel(
      data = salary_states |> filter(year == max(year), !is.na(avg)),
      aes(label = region, colour = group),
      size = 2.1, label.padding = 0.1, label.size = 0,
      fill = alpha(CLR_BG, 0.7), show.legend = FALSE,
      nudge_x = 0.2, direction = "y", hjust = 0, segment.size = 0.2
    ) +
    annotate("text", x = max(de_line$year) + 0.15,
             y = tail(de_line$avg[order(de_line$year)], 1) + 80,
             label = "DE avg.", colour = CLR_DE, size = 2.2, hjust = 0) +
    scale_colour_manual(values = c("West" = CLR_WEST, "East" = CLR_EAST), name = NULL) +
    scale_x_continuous(
      breaks = sort(unique(salary_states$year)),
      expand = expansion(mult = c(0.02, 0.22))
    ) +
    scale_y_continuous(labels = euro_labels) +
    labs(
      title    = "**C** Avg. salary trend by state, 2019\u20132026",
      subtitle = "Dashed line = national average",
      x = NULL, y = "Gross monthly salary (\u20ac)"
    ) +
    base_theme +
    theme(
      legend.position = "none",
      axis.text.x     = element_text(size = 6.5, angle = 30, hjust = 1)
    )
}

build_ribbon <- function() {
  df <- salary_states |> filter(!is.na(avg), !is.na(q1), !is.na(q3))
  ggplot(df, aes(x = year)) +
    geom_ribbon(aes(ymin = q1, ymax = q3, fill = group), alpha = 0.25) +
    geom_line(aes(y = avg, colour = group), linewidth = 0.6) +
    geom_point(aes(y = avg, colour = group), size = 1.2) +
    facet_wrap(~region_f, ncol = 4) +
    scale_fill_manual(values   = c("West" = CLR_WEST, "East" = CLR_EAST), name = NULL) +
    scale_colour_manual(values = c("West" = CLR_WEST, "East" = CLR_EAST), name = NULL) +
    scale_x_continuous(breaks = c(2019, 2022, 2026), labels = c("'19", "'22", "'26")) +
    scale_y_continuous(
      labels = label_number(scale = 1e-3, suffix = "k", prefix = "\u20ac"),
      limits = c(3000, 6000),
      oob    = scales::squish
    ) +
    labs(
      title    = "**C** Q1\u2013avg\u2013Q3 salary band per state, 2019\u20132026",
      subtitle = "Shaded = Q1\u2013Q3 range \u00b7 Line = mean \u00b7 Shared y-axis \u20ac3k\u2013\u20ac6k (BaWü Q3 outlier squished)",
      x = NULL, y = "Gross monthly salary (\u20ac)"
    ) +
    base_theme +
    theme(
      strip.text      = element_text(size = 6, face = "bold"),
      axis.text       = element_text(size = 6),
      legend.position = "bottom",
      panel.spacing   = unit(0.3, "lines")
    )
}

# ── 5. Shared annotation ──────────────────────────────────────────────────────

anno <- plot_annotation(
  title    = "Bioinformatiker/in salaries in Germany by federal state",
  subtitle = paste0(
    "Gross monthly salary \u00b7 ",
    "Source: gehaltsvergleich.com (scraped 2019\u20132026 via Wayback Machine)"
  ),
  caption  = paste0(
    "\u25cb = Q1 \u00b7 \u25c6 = Mean \u00b7 \u25cb = Q3 \u00b7 ",
    "Blue = West Germany \u00b7 Red = East Germany"
  ),
  theme = theme(
    plot.background = element_rect(fill = CLR_BG, colour = NA),
    plot.title      = element_text(size = 13, face = "bold",    margin = margin(b = 3)),
    plot.subtitle   = element_text(size = 9,  colour = "grey40", margin = margin(b = 6)),
    plot.caption    = element_text(size = 7,  colour = "grey55", margin = margin(t = 6))
  )
)

save_fig <- function(fig, stem, w = 297, h = 210) {
  for (ext in c("png", "pdf")) {
    fn <- paste0(stem, ".", ext)
    ggsave(fn, plot = fig, width = w, height = h, units = "mm",
           dpi = OUT_DPI, bg = CLR_BG,
           device = if (ext == "pdf") cairo_pdf else NULL)
    message("  Saved: ", fn)
  }
}

# ── 6. Build and save ─────────────────────────────────────────────────────────

message("\n--- Building panels ---")
p_map_single <- build_map_single(2026)
p_map_facet  <- build_map_facet()
p_dumbbell   <- build_dumbbell()
p_spaghetti  <- build_spaghetti()
p_ribbon     <- build_ribbon()
message("Panels OK\n")

message("--- Variant 1: single map | dumbbell | spaghetti ---")
fig_v1 <- (p_map_single | (p_dumbbell / p_spaghetti)) +
  plot_layout(widths = c(1, 1.1)) + anno
save_fig(fig_v1, "fig_v1_map_dumbbell_spaghetti")

message("--- Variant 2: single map | dumbbell | ribbon ---")
fig_v2 <- (p_map_single | (p_dumbbell / p_ribbon)) +
  plot_layout(widths = c(0.9, 1.2)) + anno
save_fig(fig_v2, "fig_v2_map_dumbbell_ribbon")

message("--- Variant 3: faceted maps | dumbbell (A4 portrait) ---")
fig_v3 <- (p_map_facet / p_dumbbell) +
  plot_layout(heights = c(1.4, 1)) + anno
save_fig(fig_v3, "fig_v3_mapmultiple_dumbbell", w = 210, h = 297)

message("\nAll figures saved. Review fig_v1, fig_v2, fig_v3 and pick your favourite.")